### ISSUE TITLE
final updates from casey

### ISSUE THREAD

**Issue by alvizek** [FlowWest/edi-feather-snorkel#14]
- [x] comparison of "units covered" and units in the fish observations table. casey indicated that there might be some situations where a unit was covered but if no fish were observed this just wasn't recorded. i'd like to do a check to see if this is happening. if it is not happening often we should just add in the 0 fish observation for the unit. this will mean we can get rid of the units_covered variable
- [x] remove section_name and section_number from the survey characteristics table. now that we have all the units mapped, these are not useful fields. remove from metadata too
- [x] DWR as funder in metadata
- [x] update the section_type field. we are not sure what this field means for the historical data. we decided to update this field using the following logic, if a survey on a given day includes units in this table (https://github.com/FlowWest/edi-feather-snorkel/blob/main/data-raw/processed-tables/snorkel_built_lookup_table.xlsx) then they are permanent, if not then random. This logic only applies to 2015 and onwards. For years before 2015 we will have to make NA.
- [x] include information from casey's comments to pascale's questions (see email I forwarded) where needed. some of these may not be needed anymore because of removing section name and number. please review the methods doc and update where needed.
- [x] double check items for the other open issue have been updated
- [x] send the data and metadata to casey and pascale for final review

**Comment by MaddeeRubenson** [comment]
>  comparison of "units covered" and units in the fish observations table. casey indicated that there might be some situations where a unit was covered but if no fish were observed this just wasn't recorded. i'd like to do a check to see if this is happening. if it is not happening often we should just add in the 0 fish observation for the unit. this will mean we can get rid of the units_covered variable

It looks like there are many cases where `units_covered` was not recorded but there are values for `unit` and `count` is either 0 or greater. `units_covered` seems unreliable and best to remove the `units_covered` variable. All `NAs` for `count` are listed as zero. 

> update the section_type field. we are not sure what this field means for the historical data. we decided to update this field using the following logic, if a survey on a given day includes units in this table (https://github.com/FlowWest/edi-feather-snorkel/blob/main/data-raw/processed-tables/snorkel_built_lookup_table.xlsx) then they are permanent, if not then random. This logic only applies to 2015 and onwards. For years before 2015 we will have to make NA.

I accomplished this by joining the `combined_snorkel_metadata` with that table by `section_number` and then doing an ifelse for permanent vs. random vs. NA. This doesn't use the `units` column in that table. Is that okay?
