### ISSUE TITLE
double checks and consistency with the mini snorkel survey

### ISSUE THREAD

**Issue by alvizek** [FlowWest/edi-feather-snorkel#9]
- [ ] Rename glide edgewater to glide margin and riffle edgewater to riffle margin (this should already be done for this dataset but good to double check
- [ ] Use traditional definitions for geomorphic units
- [ ] double check no issues with categorical variables based on joins with lookups
- [ ] Add detail to metadata field descriptions: Include definition for the difference between small and large wood, Include definition for substrate levels, Update definition of channel width
- [ ] Add funder as DWR
- [ ] Keywords: add all species, spell out Healthy Rivers and Landscapes
- [ ] Add statement in the methods that describes that methods have changed over time

**Comment by MaddeeRubenson** [comment]
- [x]  Rename glide edgewater to glide margin and riffle edgewater to riffle margin (this should already be done for this dataset but good to double check
- double checked that there are no `edgewater` attached to glide and riffle 

- [x]  Use traditional definitions for geomorphic units
- Levels = c("backwater", "glide", "glide margin", "pool", "riffle", "riffle margin", NA)
- added `NA` to channel_geomorphic_unit in fish_observations_metadata 

- [x]  double check no issues with categorical variables based on joins with lookups
- still in progress

- [ ]  Add detail to metadata field descriptions: Include definition for the difference between small and large wood, Include definition for substrate levels, Update definition of channel width
-  **QUESTION**: Where is Large and Small wood? Channel width? Don’t see these variables in the datasets 
- substrate - TODO add a definition for `6`

- [x]  Add funder as DWR
- Added funder_name = DWR; funding_description = Department of Water Resources

- [x]  Keywords: add all species, spell out Healthy Rivers and Landscapes
- added spelled out Healthy Rivers and Landscapes
- **QUESTION**: Do we still want HR&L?
- **QUESTION**: Species: do we want to spell out all 43?

- [x]  Add statement in the methods that describes that methods have changed over time
- Added the following statement to methods: The methods throughout the study did not remain consistent but it is not well-documented when they were modified.
